package com.example.progetto.database

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "transactions")
data class Transactions (
    @PrimaryKey(autoGenerate = true)
    var autogeneratedId: Long = 0L,

    var id: Long = 0L,

    var date: Long,

    val type: Int,

    @ColumnInfo(name = "ticker")
    var ticker: String,

    @ColumnInfo(name = "amount")
    var amount: Float,

    @ColumnInfo(name = "commission_ticker")
    var commissionTicker: String,

    @ColumnInfo(name = "commission")
    var commission: Float,

    var from: String,
)

